---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gran
  region: us-west-2
  version: "1.21"

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true

managedNodeGroups:
  - name: "node1"
    minSize: 3
    desiredCapacity: 4
    maxSize: 5
    volumeSize: 100
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/testing: "owned"
    instanceType: m5.xlarge
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
        cloudWatch: true