
apiVersion: v1
kind: Secret
metadata:
  name: granulate-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJncmFudWxhdGVwb2MiLCJwYXNzd29yZCI6Imc0YW45MGMhRyIsImF1dGgiOiJaM0poYm5Wc1lYUmxjRzlqT21jMFlXNDVNR01oUnc9PSJ9fX0=
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: granulate-cluster-role
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    resourceNames:
      - granulate-agent
    verbs:
    - '*'
  - apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - nodes
      - pods
      - deployments
      - daemonsets
      - statefulsets
      - replicasets
      - replicationcontrollers
    verbs:
      - '*'
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - '*'
  - apiGroups:
      - ''
      - apps
      - extensions
      - policy
    resources:
      - services
      - endpoints
      - namespaces
      - limitranges
      - resourcequotas
      - persistentvolumes
      - persistentvolumeclaims
      - poddisruptionbudget
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - nodes/spec
      - nodes/stats
      - nodes/proxy
      - nodes/metrics
    verbs:
      - get
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - granulate-cluster-role
    resources:
    - clusterroles
    verbs:
      - get
  - nonResourceURLs:
    - /version
    - /healthz
    - /healthz/*
    - /metrics
    verbs:
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: granulate-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: granulate-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: granulate-cluster-role
subjects:
  - kind: ServiceAccount
    name: granulate-service-account
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: granulate-agent
  name: granulate-agent
  namespace: default
spec:
  selector:
    matchLabels:
      app: granulate-agent
  template:
    metadata:
      labels:
        app: granulate-agent
    spec:
      containers:
      - env:
        - name: CLIENT_ID
          value: &client_id 'LiUNc8+F5jXAAIgrAneHtQ=='
        - name: SERVICE_ID
          value: &service_id 'granulate'
        - name: GAGENT_RUN_ON_K8S
          value: 'TRUE'
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: index.docker.io/granulate/gagent:latest
        imagePullPolicy: Always
        name: granulate-agent
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 256Mi
        securityContext:
          privileged: true
        tty: true
        volumeMounts:
        - mountPath: /host
          name: host-volume
      - env:
        - name: IN_CONTAINER
          value: '1'
        - name: CLIENT_ID
          value: *client_id
        - name: SERVICE_ID
          value: *service_id
        - name: ADDRESS
          value: https://containersstats.granulate.io/api/v1/stats
        - name: CONTAINER_UNITS_ADDRESS
          value: "https://containersstats.granulate.io/api/v1/container-units"
        - name: PERIOD_SECONDS
          value: '60'
        image: index.docker.io/granulate/containers_stats:latest
        imagePullPolicy: Always
        name: granulate-containers-stats
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 25m
            memory: 128Mi
        securityContext:
          privileged: true
        tty: true
      hostNetwork: true
      hostPID: true
      imagePullSecrets:
      - name: granulate-secret
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: granulate-service-account
      terminationGracePeriodSeconds: 3
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/role
        operator: Equal
        value: master
      volumes:
      - hostPath:
          path: /
        name: host-volume